/// <reference types="Cypress"/>


describe('Testes De Compras Funcionais', () => {
    it('Logar, Adentrar e Comprar.', () => {
        cy.visit("https://www.saucedemo.com/v1/")
        cy.get('[data-test="username"]').type("problem_user")
        cy.get('[data-test="password"]').type("secret_sauce")
        cy.get('#login-button').click()
        cy.get('.product_label').should('contain', 'Products')
        cy.get('.inventory_list > :nth-child(2)').click()
        cy.get(':nth-child(2) > .pricebar > .btn_primary').should('contain', 'ADD TO CART')
        cy.get(':nth-child(2) > .pricebar > .btn_primary').click()
        cy.get('.btn_secondary').should('contain', 'REMOVE')
        cy.get('.fa-layers-counter').should('contain', '1')
        cy.get('.fa-layers-counter').click()
        cy.get('.btn_action').should('contain', 'CHECKOUT')
        cy.get('.btn_action').click()
        cy.get('.subheader').should('contain', 'Checkout: Your Information')
        cy.get('[data-test="firstName"]').type("Gabriel")
        cy.get('[data-test="lastName"]').type("Magalhães")
        cy.get('[data-test="postalCode"]').type("57315-194")
        cy.get('.btn_primary').should('contain', 'CONTINUE')
        cy.get('.btn_primary').click()
        cy.get('.subheader').should('contain', 'Checkout: Overview')
        cy.get('.btn_action').click()
        cy.get('.complete-header').should('contain', 'THANK YOU FOR YOUR ORDER')
        cy.log("You bought the sauce labs bike light man! Awesome!")
    });

    it('Logar, Adentrar e Colocar nada na hora da Compra.', () => {
        cy.visit("https://www.saucedemo.com/v1/")
        cy.get('[data-test="username"]').type("problem_user")
        cy.get('[data-test="password"]').type("secret_sauce")
        cy.get('#login-button').click()
        cy.get('.product_label').should('contain', 'Products')
        cy.get('.inventory_list > :nth-child(2)').click()
        cy.get(':nth-child(2) > .pricebar > .btn_primary').should('contain', 'ADD TO CART')
        cy.get(':nth-child(2) > .pricebar > .btn_primary').click()
        cy.get('.btn_secondary').should('contain', 'REMOVE')
        cy.get('.fa-layers-counter').should('contain', '1')
        cy.get('.fa-layers-counter').click()
        cy.get('.btn_action').should('contain', 'CHECKOUT')
        cy.get('.btn_action').click()
        cy.get('.subheader').should('contain', 'Checkout: Your Information')
        cy.get('.btn_primary').click()
        cy.get('[data-test="error"]').should('contain', 'First Name is required')
    });

    it('Logar, Adentrar e Colocar só o Nome na hora da Compra.', () => {
        cy.visit("https://www.saucedemo.com/v1/")
        cy.get('[data-test="username"]').type("problem_user")
        cy.get('[data-test="password"]').type("secret_sauce")
        cy.get('#login-button').click()
        cy.get('.product_label').should('contain', 'Products')
        cy.get('.inventory_list > :nth-child(2)').click()
        cy.get(':nth-child(2) > .pricebar > .btn_primary').should('contain', 'ADD TO CART')
        cy.get(':nth-child(2) > .pricebar > .btn_primary').click()
        cy.get('.btn_secondary').should('contain', 'REMOVE')
        cy.get('.fa-layers-counter').should('contain', '1')
        cy.get('.fa-layers-counter').click()
        cy.get('.btn_action').should('contain', 'CHECKOUT')
        cy.get('.btn_action').click()
        cy.get('.subheader').should('contain', 'Checkout: Your Information')
        cy.get('[data-test="firstName"]').type("Gabriel")
        cy.get('.btn_primary').click()
        cy.get('[data-test="error"]').should('contain', 'Last Name is required')
    });

    it('Logar, Adentrar e Colocar só o Nome e Sobrenome na hora da Compra.', () => {
        cy.visit("https://www.saucedemo.com/v1/")
        cy.get('[data-test="username"]').type("problem_user")
        cy.get('[data-test="password"]').type("secret_sauce")
        cy.get('#login-button').click()
        cy.get('.product_label').should('contain', 'Products')
        cy.get('.inventory_list > :nth-child(2)').click()
        cy.get(':nth-child(2) > .pricebar > .btn_primary').should('contain', 'ADD TO CART')
        cy.get(':nth-child(2) > .pricebar > .btn_primary').click()
        cy.get('.btn_secondary').should('contain', 'REMOVE')
        cy.get('.fa-layers-counter').should('contain', '1')
        cy.get('.fa-layers-counter').click()
        cy.get('.btn_action').should('contain', 'CHECKOUT')
        cy.get('.btn_action').click()
        cy.get('.subheader').should('contain', 'Checkout: Your Information')
        cy.get('[data-test="firstName"]').type("Gabriel")
        cy.get('[data-test="lastName"]').type("Magalhães")
        cy.get('.btn_primary').click()
        cy.get('[data-test="error"]').should('contain', 'Postal Code is required')
    });
});
